### ISSUE TITLE
Disable region filter?

### ISSUE THREAD

**Issue by shillshocked** [PaulMcInnis/Better-Release-Radar#1]
This is an awesome script, but I would like to obtain releases from all regions, since I am putting out global playlists. Could this be implemented? In the meantime, I just commented out the region-specific code part.

**Comment by PaulMcInnis** [comment]
Thanks!

Glad to see this is getting some use, it's kind of a brute-force solution but it works better than spotify's own release radar bs. 

I can add a flag for this pretty easily.

**Comment by shillshocked** [comment]
The codebase has changed significantly in the new version. What's an easy way to disable region now? Did you create a flag?

**Comment by PaulMcInnis** [comment]
Hey there, you can disable region filter by commenting out L100&101 lines in main:

https://github.com/PaulMcInnis/Better-Release-Radar/blob/6ced6c49be41a561bd482b9cb758516ba80bad85/src/main.ts#L100

the new codebase features-wise has better auth and better filtering.

**Comment by PaulMcInnis** [comment]
ah actually you can do this

```
--region ""
```

**Comment by shillshocked** [comment]
Awesome, thanks!!!
