### ISSUE TITLE
You should have handling for albums with year 0000

### ISSUE THREAD

**Issue by shillshocked** [PaulMcInnis/Better-Release-Radar#2]
I get a few of these.

Try something like this, you'll have to set it to an arbitrary date in the code. Could be specified to current day like below:

```
if alb['release_date'] == "0000" or alb['release_date'] == "0000-00" or alb['release_date'] == "0000-00-00":
     alb['release_date'] = TODAY_DATE
```

**Comment by PaulMcInnis** [comment]
wow, would love to get an album URI to check this out on, they definitely seem to have pretty lax date formatting standards

**Comment by shillshocked** [comment]
Don't have one off-hand at the moment. I know that Spotify generally just takes in whatever the record labels give it. Sometimes there is only 4 digit or 6 digit precision when looking up an album, but on occasion, very rarely, there is an error (probably due to an album being removed or some other particular reason). It's also good to have this for error handling, in the case of invalid input.

**Comment by PaulMcInnis** [comment]
cool in that case yeah, I think setting it to the epoch time and logging an error message is fine.

Might be wise to avoid setting to current date just because then the temporal filtering will be bypassed with albums of an unknown date.

**Comment by shillshocked** [comment]
In my use case, it would be better to add a parameter:

```
# Inits
now = datetime.now()
RELEASE_WEEK_DAY_DEFAULT = now.strftime("%Y-%m-%d")
```

In parser:
```
	parser.add_argument(
		'--release-week-day',
		help='# current release week day.',
		required=False,
		default=RELEASE_WEEK_DAY_DEFAULT,
		type=str,
	)
```

And in the main code:

```
			if alb['release_date'] == "0000" or alb['release_date'] == "0000-00" or alb['release_date'] == "0000-00-00":
				alb['release_date'] = args.release-week-day
```

This allows you to specify the precise date you want to set albums with an error or zero date to. It's useful when doing weekly release lists where the release date is a certain day of the week (and you might not be doing it the exact day).

**Comment by shillshocked** [comment]
Found one:

spotify:album:7ofEGPMq8sFfJr70KgZu41	Jupiluxe	Bend It Like Beckham Freestyle	0000

**Comment by PaulMcInnis** [comment]
this should be fixed now that we are using `spotify-web-api-node`
